name: GitHub Self Updating Repository Demo

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-jobs:
    name: Update date
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Modify date and tiem
      run: |
        date >> README.md
        cat README.md
    - name: Push to repository
      run: |
        git config --global user.name "Sanzo00"
        git config --global user.email "arrangeman@163.com"
        now=$(date)
        git add -A
        git commit -m "Auto push on ${now}"
        git push
        
